print("Hello Siddh")
print("Welcome to Python Programming")
print("This is my first Python program")
print("I am learning Python")
print("Python is a great programming language")
print("I am enjoying learning Python")
print("I will become a Python developer")
print("I am excited to learn more about Python")
print("Python is used in many fields like web development, data science, machine learning, and more")
print("I am grateful for the opportunity to learn Python")
print("I will practice Python every day to improve my skills")
print("This is a new line added directly in github which I want to sync")
